### ISSUE TITLE
Documents do not save with onlyoffice-documentserver 7.0.0

### ISSUE THREAD

**Issue by poandlsl** [xwikisas/application-onlyoffice-connector#24]
After upgrading OnlyOffice Document server to 7.0.0, document attachments in XWiki cannot be saved, and all edits are lost.  When a user tries to save a document, the error "Failed to save the page. Reason: Request error [downloading]" appears briefly at the bottom of the page.  The browser dev tools shows an error 404 trying the reach the page "[object%20Object]" after click the save button.

Downgrading to OnlyOffice Document server 6.4.2 allows users to save documents again.

XWiki version: 14.0
OnlyOffice connector version: 1.6

**Comment by Tragen** [comment]
I have the same problem.
Same error in the console.
Please fix it.

**Comment by Tragen** [comment]
I find it very strange that we pay for this extension in xwiki and there is no response and no fix since weeks from the developer(s)

**Comment by mflorea** [comment]
@Tragen if you have a paid license then you are entitled to get support from XWiki SAS but you need to use the right channels, as indicated in the email you received after your purchase. Anyone can report issues on GitHub (and we appreciate this very much), including those that don't have a license or that have a trial license, so our support engineers handle these issues with low priority compared to the issues received on the support channel (from paying customers).

Now, I'm not entirely sure that the paid support includes making the application work with the latest version of the OnlyOffice document server in a few weeks, especially when the latest version is a major jump from 6.x to 7.x which includes breaking changes, but the support team will clarify this with you.

Personally I don't see this as a blocking issue as long as the application works fine with the OnlyOffice document server 6.x. If you have problems with the 6.x version that prevent you from using the application then you should mention them because it can increase the priority of this issue. In any case, please contact the support team if you have a paid license and the support team will pressure the developers to fix this issue as soon as possible.

**Comment by Tragen** [comment]
I did but the only answer I got that the description says that this works only with the 6.x version. But if you look at archive.org, the answer was added after I asked for it. Not very nice.

**Comment by Tragen** [comment]
Thank you, when will it be available in xwiki?

**Comment by mflorea** [comment]
Hi, 2.0-rc-2 version can be installed, **for testing**, with the Extension Manager (advanced install). The QA team is currently finalizing their tests and if all goes well we'll release 2.0 final shortly.
